/**
 * Gallery photography — the client's own shoots, taken from their existing
 * site. Alt text is theirs. Files live in `public/gallery/`; to add or replace
 * a photograph, drop the file in and add an entry here.
 *
 * No stock, no fabricated client or event imagery.
 */

export type GalleryImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
  subject: GallerySubject;
  place: string;
};

export type GallerySubject =
  | "cullinan"
  | "wraith"
  | "g-wagon"
  | "urus"
  | "sf90"
  | "collection";

export const galleryFilters = [
  { id: "all", label: "Everything" },
  { id: "cullinan", label: "Rolls-Royce Cullinan" },
  { id: "wraith", label: "Rolls-Royce Wraith" },
  { id: "g-wagon", label: "Mercedes-AMG G-Wagon" },
  { id: "urus", label: "Lamborghini Urus" },
  { id: "sf90", label: "Ferrari SF90" },
  { id: "collection", label: "The collection" },
] as const;

export const gallery: readonly GalleryImage[] = [
  {
    src: "/gallery/london-01.jpg",
    width: 1600,
    height: 1066,
    alt: "Rolls-Royce Cullinan and Ferrari SF90 at Canary Wharf",
    subject: "collection",
    place: "Canary Wharf, London",
  },
  {
    src: "/gallery/london-02.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 Stradale",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-03.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 rear view",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-04.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 rear quarter",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-05.jpg",
    width: 1600,
    height: 2400,
    alt: "Ferrari SF90 at dusk",
    subject: "sf90",
    place: "Canary Wharf, London",
  },
  {
    src: "/gallery/london-06.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan rear lights",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-07.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan Black Badge",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-08.jpg",
    width: 1600,
    height: 1067,
    alt: "Spirit of Ecstasy detail",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-09.jpg",
    width: 1600,
    height: 2400,
    alt: "Ferrari SF90 portrait",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-10.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 side profile",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-11.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 at Peninsula Hotel",
    subject: "sf90",
    place: "Hotel entrances, London",
  },
  {
    src: "/gallery/london-12.jpg",
    width: 1600,
    height: 1067,
    alt: "Both vehicles at Peninsula Ballroom",
    subject: "collection",
    place: "Hotel entrances, London",
  },
  {
    src: "/gallery/london-13.jpg",
    width: 1600,
    height: 1067,
    alt: "Collection at luxury hotel",
    subject: "collection",
    place: "Hotel entrances, London",
  },
  {
    src: "/gallery/london-14.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan at Peninsula",
    subject: "cullinan",
    place: "Hotel entrances, London",
  },
  {
    src: "/gallery/london-15.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 wheel detail",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-16.jpg",
    width: 1600,
    height: 2400,
    alt: "Ferrari SF90 rear at night",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-17.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 at hotel entrance",
    subject: "sf90",
    place: "Hotel entrances, London",
  },
  {
    src: "/gallery/london-18.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 front quarter",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-19.jpg",
    width: 1600,
    height: 2400,
    alt: "Ferrari SF90 portrait shot",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-20.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 rear three quarter",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-21.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 front view",
    subject: "sf90",
    place: "London",
  },
  {
    src: "/gallery/london-22.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan at entrance",
    subject: "cullinan",
    place: "Hotel entrances, London",
  },
  {
    src: "/gallery/london-23.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan low angle",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-24.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan side profile",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-25.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan rear quarter",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-26.jpg",
    width: 1600,
    height: 2400,
    alt: "Rolls-Royce Cullinan portrait",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-27.jpg",
    width: 1600,
    height: 1067,
    alt: "Collection at O2 Arena",
    subject: "collection",
    place: "North Greenwich, London",
  },
  {
    src: "/gallery/london-28.jpg",
    width: 1600,
    height: 1067,
    alt: "Both vehicles at North Greenwich",
    subject: "collection",
    place: "North Greenwich, London",
  },
  {
    src: "/gallery/london-29.jpg",
    width: 1600,
    height: 1067,
    alt: "Collection with O2 backdrop",
    subject: "collection",
    place: "North Greenwich, London",
  },
  {
    src: "/gallery/london-30.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari with Cullinan at O2",
    subject: "collection",
    place: "North Greenwich, London",
  },
  {
    src: "/gallery/london-31.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce front grille detail",
    subject: "cullinan",
    place: "London",
  },
  {
    src: "/gallery/london-32.jpg",
    width: 1600,
    height: 1067,
    alt: "Rolls-Royce Cullinan at O2",
    subject: "cullinan",
    place: "North Greenwich, London",
  },
  {
    src: "/gallery/london-33.jpg",
    width: 1600,
    height: 1067,
    alt: "Collection at North Greenwich Station",
    subject: "collection",
    place: "North Greenwich, London",
  },
  {
    src: "/gallery/london-34.jpg",
    width: 1600,
    height: 1067,
    alt: "Ferrari SF90 and Cullinan together",
    subject: "collection",
    place: "London",
  },
  {
    src: "/gallery/london-35.jpg",
    width: 1600,
    height: 1067,
    alt: "Both vehicles evening shot",
    subject: "collection",
    place: "London",
  },
  {
    src: "/gallery/london-36.jpg",
    width: 1600,
    height: 1067,
    alt: "Detail shot, both vehicles",
    subject: "collection",
    place: "London",
  },
  {
    src: "/gallery/studio-01.jpg",
    width: 1600,
    height: 1216,
    alt: "Rolls-Royce Cullinan side profile in the workshop",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-02.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Cullinan front three quarter",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-03.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Cullinan rear cabin",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-04.jpg",
    width: 1600,
    height: 1200,
    alt: "Cullinan illuminated door sill",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-05.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Cullinan rear three quarter",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-06.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Cullinan rear",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-07.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Cullinan front cabin",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-08.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Cullinan steering wheel and dials",
    subject: "collection",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-09.jpg",
    width: 1600,
    height: 1200,
    alt: "Spirit of Ecstasy",
    subject: "cullinan",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-10.jpg",
    width: 1600,
    height: 1200,
    alt: "Mercedes-AMG G-Wagon front three quarter",
    subject: "g-wagon",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-11.jpg",
    width: 1600,
    height: 1200,
    alt: "Mercedes-AMG G-Wagon front",
    subject: "g-wagon",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-12.jpg",
    width: 1600,
    height: 1200,
    alt: "Mercedes-AMG G-Wagon cabin",
    subject: "g-wagon",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-13.jpg",
    width: 1600,
    height: 1200,
    alt: "Mercedes-AMG G-Wagon side profile",
    subject: "g-wagon",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-14.jpg",
    width: 1600,
    height: 1200,
    alt: "Mercedes-AMG G-Wagon rear",
    subject: "g-wagon",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-15.jpg",
    width: 1600,
    height: 1200,
    alt: "Mercedes-AMG G-Wagon cockpit",
    subject: "g-wagon",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-16.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 front",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-17.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 front three quarter",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-18.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 with the door raised",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-19.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 rear three quarter",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-20.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 rear",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-21.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 cockpit",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-22.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 engine cover",
    subject: "sf90",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-23.jpg",
    width: 1600,
    height: 1200,
    alt: "Lamborghini Urus front",
    subject: "urus",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-24.jpg",
    width: 1600,
    height: 1200,
    alt: "Lamborghini Urus side profile",
    subject: "urus",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-25.jpg",
    width: 1600,
    height: 1200,
    alt: "Lamborghini Urus cockpit",
    subject: "urus",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-26.jpg",
    width: 1600,
    height: 1200,
    alt: "Lamborghini door projection",
    subject: "urus",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-27.jpg",
    width: 1600,
    height: 1200,
    alt: "Rolls-Royce Wraith Black Badge",
    subject: "wraith",
    place: "Workshop",
  },
  {
    src: "/gallery/studio-28.jpg",
    width: 1600,
    height: 1200,
    alt: "Ferrari SF90 with the door raised",
    subject: "sf90",
    place: "Workshop",
  },
];
